INSERT ALL
INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (1, 'Opel', 'Astra', 'WA 65098', 70, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (2, 'Opel', 'Vectra', 'WA 37083', 80, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (3, 'Opel', 'Astra', 'SK 34074', 60, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (4, 'Mercedes', 'C Class', 'PO 65064', 100, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (5, 'Mercedes', 'C Class', 'PO 04492', 100, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (6, 'Mercedes', 'C Class', 'SK 43083', 120, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (7, 'Mercedes', 'S Class', 'WI 65014', 140, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (8, 'Volkswagen', 'Passat', 'WA 55071', 90, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (9, 'Volkswagen', 'Passat', 'SK 09132', 85, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (10, 'Volkswagen', 'Caddy', 'WA 61094', 95, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (11, 'Volkswagen', 'Caddy', 'PO 30961', 80, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (12, 'Fiat', '500', 'SK 08410', 75, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (13, 'Fiat', '500', 'WA 10624', 90, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (14, 'Ford', 'Focus', 'PO 65096', 75, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (15, 'Ford', 'Focus', 'WA 45810', 90, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (16, 'Ford', 'Mondeo', 'SK 56025', 90, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (17, 'Ford', 'Mondeo', 'PO 34974', 80, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (18, 'Audi', 'A4', 'WA 4418', 105, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (19, 'Audi', 'A4', 'WA 46926', 105, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (20, 'Audi', 'A4', 'SK 08246', 110, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (21, 'Audi', 'A6', 'PO 56916', 120, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (22, 'Audi', 'A6', 'WA 46987', 70, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (23, 'Toyota', 'Corolla', 'SK 56925', 70, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (24, 'Toyota', 'Corolla', 'PO 46708', 70, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (25, 'Toyota', 'Corolla', 'PO 46707', 70, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (26, 'Toyota', 'Corolla', 'WA 69254', 80, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (27, 'Toyota', 'Corolla', 'WA 46569', 80, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (28, 'Peugeot', '207', 'SK 08279', 85, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (29, 'Peugeot', '207', 'SK 56649', 85, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (30, 'Peugeot', '207', 'PO 46986', 80, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (31, 'Peugeot', '508', 'WA 56758', 95, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (32, 'Renault', 'Megane', 'WA 38649', 95, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (33, 'Renault', 'Megane', 'SK 58651', 90, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (34, 'Renault', 'Clio', 'SK 67855', 60, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (35, 'Renault', 'Clio', 'PO 57108', 55, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (36, 'Renault', 'Clio', 'WA 59715', 65, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (37, 'Renault', 'Clio', 'SK 47752', 60, 'KAT')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (38, 'Skoda', 'Fabia', 'WA 81768', 80, 'WAR')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (39, 'Skoda', 'Fabia', 'PO 96779', 70, 'POZ')
  INTO auta (id,marka,model_auta,num_rej,cena_dzien, oddzial) VALUES (40, 'Skoda', 'Fabia', 'WA 93647', 80, 'WAR')
SELECT * FROM dual;